name: single-spa-aurelia

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn

      - uses: actions/setup-node@v1
        with:
          node-version: 12.12

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --pure-lockfile --non-interactive --no-progress

      - name: Run ESLint
        run: yarn lint

      - name: Run Jest
        run: yarn test:ci

      - name: Build library
        run: yarn build

      - name: Install packages for integration apps
        run: yarn install:integration

      - name: Build integration apps
        run: yarn build:integration

      - name: Run end-to-end tests via Cypress
        run: yarn test:ci:integration
